---

#
# centos-selinux
#
# This task ensures that selinux is set to permissive on RedHat family
# machines.
#

# Set selinux to permissive
- selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat"
