---

#
# nagios-client
#
# This role configures the system to be a client that can be monitored
# from the nagios master server.
#

# Include the distro variables from the "vars" directory
- include_vars: "{{ ansible_os_family }}.yml"

# CentOS packages
- name: Install nrpe packages
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - nrpe
    - nagios-plugins-all
    - nagios-plugins-check-updates
    - nagios-plugins-nrpe
    - nagios-plugins-openmanage
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

# Ubuntu packages
- name: Install nrpe packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - nagios-nrpe-server
    - nagios-plugins-basic
    - nagios-plugins-common
    - nagios-plugins-standard
    - nagios-plugins-extra
  when: ansible_distribution == "Ubuntu"

# OS agnostic tasks
- name: Copy down nagios nrpe config template file
  template:
    src: templates/nrpe.cfg.j2
    dest: /etc/nagios/nrpe.cfg
    owner: root
    group: root
    mode: 0664
  notify: restart nrpe

- name: Remove the default /etc/nagios/nrpe.d/ directory
  file:
    path: /etc/nagios/nrpe.d
    state: absent

- name: Ensure /etc/nrpe.d config directory exists
  file:
    path: /etc/nrpe.d
    state: directory
    mode: 0755

- name: Copy down default nagios checks template file
  template:
    src: templates/default-checks.cfg.j2
    dest: /etc/nrpe.d/defaults.cfg
    owner: root
    group: root
    mode: 0664
  notify: restart nrpe

- name: Copy down custom checks
  synchronize:
    src: files/plugins/
    dest: "{{ nrpe_lib }}/"
    delete: no
    perms: yes
  notify: restart nrpe
