---

#
# nagios server handlers
#
# Restart only when changes are made.
#

- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes

- name: restart nagios
  service:
    name: nagios
    state: restarted
    enabled: yes
