---

#
# centos-firewalld
#
# This role configures the firewalld service on on RedHat family
# machines.
#

- name: Ensure firewalld is disabled
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_os_family == "RedHat"
